de: kdePlasmaX

bindings:

#- key: Space
#  release: true
#  # TODO: может обрабатывать релиз без предварительного press возможно изза этого проблема
#  # TODO: может сделать тогда clear space
#  #combination: Shift + Space
#  cmd: xdotool type " "
#

#- key: CapsLock + Space
#  release: true
#  cmd: 'xdotool keyup 66; xdotool type --clearmodifiers "_"; xdotool keydown 66'

######## Languages
- key: Alt_L
  release: true
  cmd: xkb-switch -s us

- key: Alt_R
  release: true
  cmd: xkb-switch -s ru

######## Backspace, delete, enter, escape
- key: CapsLock
  release: true
  combination: Backspace
- key: Alt_R + CapsLock
  release: true
  combination: Ctrl + Backspace

- key: Shift_L
  release: true
  combination: Delete
- key: Alt_R + Shift_L
  release: true
  combination: Ctrl + Delete

- key: Shift_R
  release: true
  combination: Enter

- key: Ctrl_R
  release: true
  cmd: 'xdotool key Escape'

########## Macroses
# Make new line and move cursor to it
- key: Shift_L + Shift_R
  release: true
  actions:
    - action: combination
      combination: End
    - action: combination
      combination: Enter
# Make new line and return back
- key: Alt_L + Shift_R
  release: true
  actions:
    - action: combination
      combination: Enter
    - action: combination
      combination: Ctrl + Left
# Remove content of the line
- key: Ctrl_R + CapsLock
  release: true
  actions:
    - action: combination
      combination: End
    - action: combination
      combination: Shift + Home
    - action: combination
      combination: Backspace
# Remove whole line
- key: Ctrl_R + Shift_L
  release: true
  actions:
    - action: combination
      combination: End
    - action: combination
      combination: Shift + Home
    - action: combination
      combination: Backspace
    - action: combination
      combination: Delete
# Remove content of line with cutting to the buffer
- key: Ctrl_R + Alt_L + CapsLock
  release: true
  actions:
    - action: combination
      combination: End
    - action: combination
      combination: Shift + Home
    - action: combination
      combination: Ctrl + x
# Remove line with cutting to the buffer
- key: Ctrl_R + Alt_L + Shift_L
  release: true
  actions:
    - action: combination
      combination: End
    - action: combination
      combination: Shift + Home
    - action: combination
      combination: Ctrl + x
    - action: combination
      combination: Delete
# Duplicate the selection at new line
- key: Alt_R + Alt_L
  release: true
  actions:
    - action: combination
      combination: Ctrl + c
    - action: combination
      combination: Left
    - action: combination
      combination: Enter
    - action: combination
      combination: Up
    - action: combination
      combination: Ctrl + v
# SELECTION BY WHOLE LINE
- key: Alt_R + j
  actions:
    - action: combination
      combination: End
    - action: combination
      combination: Shift + Home
- key: Alt_R + k
  actions:
    - action: combination
      combination: End
    - action: combination
      combination: Shift + Up
    - action: combination
      combination: Shift + Home
- key: Alt_R + l
  actions:
    - action: combination
      combination: Home
    - action: combination
      combination: Shift + Down
    - action: combination
      combination: Shift + End
- key: Alt_R + Semicolon
  actions:
    - action: combination
      combination: Home
    - action: combination
      combination: Shift + End


######## ARROWS
- key: Alt_L + j
  combination: Left
- key: Alt_L + k
  combination: Up
- key: Alt_L + l
  combination: Down
- key: Alt_L + Semicolon
  combination: Right
######## FORCED ARROWS
- key: Alt_L + Shift + j
  combination: Ctrl + Left
- key: Alt_L + Shift + k
  cmd: 'xdotool key --delay 2 --clearmodifiers 111 111 111'
- key: Alt_L + Shift + l
  cmd: 'xdotool key --delay 2 --clearmodifiers 116 116 116'
#cmd: 'xdotool keyup 66; xdotool key --clearmodifiers 116 116 116; xdotool keydown 66'
- key: Alt_L + Shift + Semicolon
  combination: Ctrl + Right

######## HOME, END
- key: Alt_L + u
  combination: Home
- key: Alt_L + i
  combination: End

######## FORCED HOME, END (start and end of page)
- key: Alt_L + Shift + u
  combination: Ctrl + Home
- key: Alt_L + Shift + i
  combination: Ctrl + End

######### MOVE SCREEN by 7 LINES
- key: Alt_L + h
  cmd: 'xdotool click --clearmodifiers 4'
- key: Alt_L + n
  cmd: 'xdotool click --clearmodifiers 5'

######## PAGE UP, PAGE DOWN
- key: Alt_L + Shift + h
  combination: PgUp
- key: Alt_L + Shift + n
  combination: PgDown

######### SELECT
- key: CapsLock + j
  #combination: Shift + Left
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Left
- key: CapsLock + k
  #combination: Shift + Up
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Up
- key: CapsLock + l
  #combination: Shift + Down
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Down
- key: CapsLock + Semicolon
  #combination: Shift + Right
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Right
######### FORCED SELECT
- key: CapsLock + Alt + j
  #combination: Shift + Ctrl + Left
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Ctrl + Left
- key: CapsLock + Alt + k
  cmd: 'xdotool keyup 66; xdotool key --clearmodifiers Shift+111 Shift+111 Shift+111; xdotool keydown 66'
- key: CapsLock + Alt + l
  cmd: 'xdotool keyup 66; xdotool key --clearmodifiers Shift+116 Shift+116 Shift+116; xdotool keydown 66'
- key: CapsLock + Alt + Semicolon
  #combination: Shift + Ctrl + Right
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Ctrl + Right
######### SELECT HOME, END
- key: CapsLock + u
  #combination: Shift + Home
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Home
- key: CapsLock + i
  #combination: Shift + End
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + End
######### FORCED SELECT HOME, END (to start/end of whole page)
- key: CapsLock + Alt + u
  #combination: Shift + Ctrl + Home
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Ctrl + Home
- key: CapsLock + Alt + i
  #combination: Shift + Ctrl + End
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + Ctrl + End
######### SELECT PAGE UP, PAGE DOWN
- key: CapsLock + h
  #combination: Shift + PgUp
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + PgUp
- key: CapsLock + n
  #combination: Shift + PgDown
  actions:
    - action: combination
      clearCaps: true
      combination: Shift + PgDown

######### Numbers
- key: Alt_R + a
  cmd: xdotool type --clearmodifiers "0"
- key: Alt_R + x
  cmd: xdotool type --clearmodifiers "1"
- key: Alt_R + c
  cmd: xdotool type --clearmodifiers "2"
- key: Alt_R + v
  cmd: xdotool type --clearmodifiers "3"
- key: Alt_R + s
  cmd: xdotool type --clearmodifiers "4"
- key: Alt_R + d
  cmd: xdotool type --clearmodifiers "5"
- key: Alt_R + f
  cmd: xdotool type --clearmodifiers "6"
- key: Alt_R + w
  cmd: xdotool type --clearmodifiers "7"
- key: Alt_R + e
  cmd: xdotool type --clearmodifiers "8"
- key: Alt_R + r
  cmd: xdotool type --clearmodifiers "9"
- key: Alt_R + t
  cmd: xdotool type --clearmodifiers "+"
- key: Alt_R + q
  cmd: xdotool type --clearmodifiers "-"
- key: Alt_R + z
  cmd: xdotool type --clearmodifiers "/"
  #cmd: xdotool type --clearmodifiers $'\u002F'
- key: Alt_R + b
  cmd: xdotool type --clearmodifiers "*"
- key: Alt_R + g
  cmd: xdotool type --clearmodifiers "="

######## Symbols
# symbol _
#- key: CapsLock + Space
#  release: true
#  cmd: 'xdotool keyup 66; xdotool type "_"; xdotool keydown 66'
#  actions:
#    - action: combination
#      clearCaps: true
#      combination: Shift + Minus
# key y
- key: Alt + y
  cmd: xdotool type --clearmodifiers "@"
# key m
- key: Alt + m
  cmd: xdotool type --clearmodifiers "_"
# key o
- key: Alt + o
  cmd: xdotool type --clearmodifiers ":"
# key p
- key: Alt + p
  cmd: xdotool type --clearmodifiers ";"
# key [
  # level1 - |
  # +shift - &
- key: Alt + [
  cmd: xdotool type --clearmodifiers "#"
# key ]
  # level1 - \
  # +shift - ~
- key: Alt + ]
  cmd: xdotool type --clearmodifiers "$"
# key '
  # level1 - '
  # +shift - `
# TODO: doesn't work in firefox
- key: Alt + Apostrophe
  cmd: xdotool type '"'
  #cmd: "xdotool type $'\u0022'"
# key '
  # level1 - ,
  # +shift - ?
# TODO: doesn't work in firefox
- key: Alt + Slash
  cmd: "xdotool type $'\u003F'"
  ### this is !
  #cmd: xdotool type --clearmodifiers $'\u0021'

- key: CapsLock + Slash
  cmd: "xdotool keyup 66; xdotool type --clearmodifiers $'\u0021'; xdotool keydown 66"

- key: CapsLock + ,
  cmd: 'xdotool keyup 66; xdotool type --clearmodifiers "<"; xdotool keydown 66'
- key: CapsLock + .
  cmd: 'xdotool keyup 66; xdotool type --clearmodifiers ">"; xdotool keydown 66'
- key: Alt_L + ,
  cmd: xdotool type --clearmodifiers "("
- key: Alt_L + .
  cmd: xdotool type --clearmodifiers ")"

######## DE
# konsole
- key: CapsLock + t
  cmd: konsole
# yakuake
- key: CapsLock + y
  deShortcut: 'yakuake: toggle-window-state'

- key: CapsLock + q
  deShortcut: 'kwin: Window Close'
- key: CapsLock + w
  deShortcut: 'kwin: Window Maximize'
- key: CapsLock + Alt + w
  deShortcut: 'kwin: Window Maximize Vertical'
- key: CapsLock + Shift + w
  deShortcut: 'kwin: Window Maximize Horizontal'
- key: CapsLock + e
  deShortcut: 'kwin: Window Minimize'

- key: CapsLock + g
  deShortcut: 'kwin: Switch to Next Desktop'
- key: CapsLock + r
  deShortcut: 'kwin: Window to Next Screen'
- key: CapsLock + v
  deShortcut: 'kwin: Window to Next Desktop'

- key: CapsLock + 7
  deShortcut: 'kmix: mute'

- key: CapsLock + 6
  deShortcut: 'kmix: mic_mute'

# Walk Through Windows
# Walk Through Windows of Current Application

  #- key: k
#  mod:
#    - CapsLock
#  cmd: xdotool key --clearmodifiers 111
#
#- key: l
#  mod:
#    - CapsLock
#  cmd: xdotool key --clearmodifiers 116
#
#- key: Apostrophe
#  mod:
#    - CapsLock
#  cmd: xdotool key --clearmodifiers 114

  #- key: CapsLock
  #  mod:
  #    - Alt_R
  #  cmd: xdotool key --clearmodifiers 119

#- key: Alt + CapsLock
#  deShortcut: 'kwin: Walk Through Windows'
#  #cmd: qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Walk Through Windows'

#- key: Alt_L + Shift_L
#  cmd: qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Walk Through Windows of Current Application'
